// seeds/markets.js — Pre-seeded spot trading markets
// 10 crypto + 11 synthetic equity + 1 hive-native = 22 markets

const SYNTHETIC_DISCLAIMER = {
  synthetic_only: true,
  not_a_security: true,
  disclaimer: 'Agent-to-agent synthetic position. Not a real security. No ownership of underlying asset.',
  legal_notice: 'HiveExchange synthetic equity markets are agent-to-agent positions only. No real shares are bought, sold, or custodied. Agents trade price exposure only, settled in USDC. This is not investment advice and does not constitute securities trading. All settlements are between autonomous AI agents operating under Hive DID governance.',
  settlement_currency: 'USDC',
  underlying_price_source: 'oracle_reference_only',
};

export const SEED_MARKETS = [
  // ── Crypto ──────────────────────────────────────────────────────────────────
  {
    id: 'mkt_btc_usdc',
    symbol: 'BTC/USDC',
    base_asset: 'BTC',
    quote_asset: 'USDC',
    market_type: 'spot',
    maker_fee_pct: 0.10,
    taker_fee_pct: 0.18,
    metadata: { asset_class: 'crypto', coingecko_id: 'bitcoin', price_source: 'coingecko_live' },
  },
  {
    id: 'mkt_eth_usdc',
    symbol: 'ETH/USDC',
    base_asset: 'ETH',
    quote_asset: 'USDC',
    market_type: 'spot',
    maker_fee_pct: 0.10,
    taker_fee_pct: 0.18,
    metadata: { asset_class: 'crypto', coingecko_id: 'ethereum', price_source: 'coingecko_live' },
  },
  {
    id: 'mkt_sol_usdc',
    symbol: 'SOL/USDC',
    base_asset: 'SOL',
    quote_asset: 'USDC',
    market_type: 'spot',
    maker_fee_pct: 0.10,
    taker_fee_pct: 0.18,
    metadata: { asset_class: 'crypto', coingecko_id: 'solana', price_source: 'coingecko_live' },
  },
  {
    id: 'mkt_aleo_usdc',
    symbol: 'ALEO/USDC',
    base_asset: 'ALEO',
    quote_asset: 'USDC',
    market_type: 'spot',
    maker_fee_pct: 0.10,
    taker_fee_pct: 0.18,
    metadata: { asset_class: 'crypto', coingecko_id: 'aleo', price_source: 'coingecko_live', settlement_rail: 'aleo' },
  },
  {
    id: 'mkt_usad_usdc',
    symbol: 'USAD/USDC',
    base_asset: 'USAD',
    quote_asset: 'USDC',
    market_type: 'spot',
    maker_fee_pct: 0.05,
    taker_fee_pct: 0.08,
    metadata: { asset_class: 'crypto', paxos_backed: true, anonymous: true, aleo_zk: true, price_source: 'peg_1_00', settlement_rail: 'usad' },
  },
  {
    id: 'mkt_bnb_usdc',
    symbol: 'BNB/USDC',
    base_asset: 'BNB',
    quote_asset: 'USDC',
    market_type: 'spot',
    maker_fee_pct: 0.10,
    taker_fee_pct: 0.18,
    metadata: { asset_class: 'crypto', coingecko_id: 'binancecoin', price_source: 'coingecko_live' },
  },
  {
    id: 'mkt_avax_usdc',
    symbol: 'AVAX/USDC',
    base_asset: 'AVAX',
    quote_asset: 'USDC',
    market_type: 'spot',
    maker_fee_pct: 0.10,
    taker_fee_pct: 0.18,
    metadata: { asset_class: 'crypto', coingecko_id: 'avalanche-2', price_source: 'coingecko_live' },
  },
  {
    id: 'mkt_matic_usdc',
    symbol: 'MATIC/USDC',
    base_asset: 'MATIC',
    quote_asset: 'USDC',
    market_type: 'spot',
    maker_fee_pct: 0.10,
    taker_fee_pct: 0.18,
    metadata: { asset_class: 'crypto', coingecko_id: 'matic-network', price_source: 'coingecko_live' },
  },
  {
    id: 'mkt_arb_usdc',
    symbol: 'ARB/USDC',
    base_asset: 'ARB',
    quote_asset: 'USDC',
    market_type: 'spot',
    maker_fee_pct: 0.10,
    taker_fee_pct: 0.18,
    metadata: { asset_class: 'crypto', coingecko_id: 'arbitrum', price_source: 'coingecko_live' },
  },
  {
    id: 'mkt_op_usdc',
    symbol: 'OP/USDC',
    base_asset: 'OP',
    quote_asset: 'USDC',
    market_type: 'spot',
    maker_fee_pct: 0.10,
    taker_fee_pct: 0.18,
    metadata: { asset_class: 'crypto', coingecko_id: 'optimism', price_source: 'coingecko_live' },
  },

  // ── Synthetic Equities ───────────────────────────────────────────────────────
  {
    id: 'mkt_aapl_usdc',
    symbol: 'AAPL/USDC',
    base_asset: 'AAPL',
    quote_asset: 'USDC',
    market_type: 'spot',
    maker_fee_pct: 0.15,
    taker_fee_pct: 0.25,
    metadata: { asset_class: 'synthetic_equity', reference_price_usd: 198.50, ...SYNTHETIC_DISCLAIMER },
  },
  {
    id: 'mkt_msft_usdc',
    symbol: 'MSFT/USDC',
    base_asset: 'MSFT',
    quote_asset: 'USDC',
    market_type: 'spot',
    maker_fee_pct: 0.15,
    taker_fee_pct: 0.25,
    metadata: { asset_class: 'synthetic_equity', reference_price_usd: 415.00, ...SYNTHETIC_DISCLAIMER },
  },
  {
    id: 'mkt_nvda_usdc',
    symbol: 'NVDA/USDC',
    base_asset: 'NVDA',
    quote_asset: 'USDC',
    market_type: 'spot',
    maker_fee_pct: 0.15,
    taker_fee_pct: 0.25,
    metadata: { asset_class: 'synthetic_equity', reference_price_usd: 875.00, ...SYNTHETIC_DISCLAIMER },
  },
  {
    id: 'mkt_googl_usdc',
    symbol: 'GOOGL/USDC',
    base_asset: 'GOOGL',
    quote_asset: 'USDC',
    market_type: 'spot',
    maker_fee_pct: 0.15,
    taker_fee_pct: 0.25,
    metadata: { asset_class: 'synthetic_equity', reference_price_usd: 175.00, ...SYNTHETIC_DISCLAIMER },
  },
  {
    id: 'mkt_amzn_usdc',
    symbol: 'AMZN/USDC',
    base_asset: 'AMZN',
    quote_asset: 'USDC',
    market_type: 'spot',
    maker_fee_pct: 0.15,
    taker_fee_pct: 0.25,
    metadata: { asset_class: 'synthetic_equity', reference_price_usd: 195.00, ...SYNTHETIC_DISCLAIMER },
  },
  {
    id: 'mkt_meta_usdc',
    symbol: 'META/USDC',
    base_asset: 'META',
    quote_asset: 'USDC',
    market_type: 'spot',
    maker_fee_pct: 0.15,
    taker_fee_pct: 0.25,
    metadata: { asset_class: 'synthetic_equity', reference_price_usd: 520.00, ...SYNTHETIC_DISCLAIMER },
  },
  {
    id: 'mkt_tsla_usdc',
    symbol: 'TSLA/USDC',
    base_asset: 'TSLA',
    quote_asset: 'USDC',
    market_type: 'spot',
    maker_fee_pct: 0.15,
    taker_fee_pct: 0.25,
    metadata: { asset_class: 'synthetic_equity', reference_price_usd: 250.00, ...SYNTHETIC_DISCLAIMER },
  },
  {
    id: 'mkt_spy_usdc',
    symbol: 'SPY/USDC',
    base_asset: 'SPY',
    quote_asset: 'USDC',
    market_type: 'spot',
    maker_fee_pct: 0.10,
    taker_fee_pct: 0.18,
    metadata: { asset_class: 'synthetic_equity', description: 'S&P 500 synthetic', reference_price_usd: 540.00, ...SYNTHETIC_DISCLAIMER },
  },
  {
    id: 'mkt_qqq_usdc',
    symbol: 'QQQ/USDC',
    base_asset: 'QQQ',
    quote_asset: 'USDC',
    market_type: 'spot',
    maker_fee_pct: 0.10,
    taker_fee_pct: 0.18,
    metadata: { asset_class: 'synthetic_equity', description: 'Nasdaq-100 synthetic', reference_price_usd: 465.00, ...SYNTHETIC_DISCLAIMER },
  },
  {
    id: 'mkt_gld_usdc',
    symbol: 'GLD/USDC',
    base_asset: 'GLD',
    quote_asset: 'USDC',
    market_type: 'spot',
    maker_fee_pct: 0.10,
    taker_fee_pct: 0.18,
    metadata: { asset_class: 'synthetic_equity', description: 'Gold synthetic', reference_price_usd: 235.00, ...SYNTHETIC_DISCLAIMER },
  },
  {
    id: 'mkt_oil_usdc',
    symbol: 'OIL/USDC',
    base_asset: 'OIL',
    quote_asset: 'USDC',
    market_type: 'spot',
    maker_fee_pct: 0.10,
    taker_fee_pct: 0.18,
    metadata: { asset_class: 'synthetic_equity', description: 'WTI crude oil synthetic', reference_price_usd: 82.00, ...SYNTHETIC_DISCLAIMER },
  },

  // ── Hive-Native ──────────────────────────────────────────────────────────────
  {
    id: 'mkt_hivecredit_usdc',
    symbol: 'HIVE-CREDIT/USDC',
    base_asset: 'HIVE-CREDIT',
    quote_asset: 'USDC',
    market_type: 'spot',
    maker_fee_pct: 0.00,
    taker_fee_pct: 0.05,
    metadata: { asset_class: 'hive_native', description: 'Hive Civilization credits — 1:1 peg with USDC, tradeable between agents', peg: '1:1 USDC', price_source: 'hive_peg' },
  },
];
