// seeds/predict.js — All 125 prediction markets
// Stable IDs pm_001–pm_125 prevent duplicate seeding on redeploy

const FOUNDER_DID = 'did:hive:f150bbec-5660-413e-b305-d8d965b47845';

export const SEED_PREDICT_MARKETS = [
  // ── WEATHER (8) ─────────────────────────────────────────────────────────────
  {
    id: 'pm_001',
    question: 'Will any US city exceed 115°F in July 2026?',
    resolution_criteria: 'YES if any official NOAA weather station in a US city records ≥115°F (46.1°C) at any point during July 2026.',
    category: 'weather',
    resolution_date: '2026-07-31T23:59:00.000Z',
  },
  {
    id: 'pm_002',
    question: 'Will the 2026 Atlantic hurricane season produce 18 or more named storms?',
    resolution_criteria: 'YES if NOAA officially names 18 or more Atlantic storms during the 2026 hurricane season (June 1 – November 30, 2026).',
    category: 'weather',
    resolution_date: '2026-11-30T23:59:00.000Z',
  },
  {
    id: 'pm_003',
    question: 'Will a tornado outbreak (5+ tornadoes in 24h) hit the Midwest in May 2026?',
    resolution_criteria: 'YES if NOAA/SPC confirms a tornado outbreak of 5 or more tornadoes within 24 hours in Midwest states (IA, IL, IN, KS, MI, MN, MO, NE, ND, OH, SD, WI) during May 2026.',
    category: 'natural_disaster',
    resolution_date: '2026-05-31T23:59:00.000Z',
  },
  {
    id: 'pm_004',
    question: 'Will a Category 4 or higher hurricane make US landfall in 2026?',
    resolution_criteria: 'YES if the National Hurricane Center confirms a Cat 4+ (≥130 mph sustained winds) hurricane makes landfall on the US mainland, Puerto Rico, or US Virgin Islands in 2026.',
    category: 'natural_disaster',
    resolution_date: '2026-11-30T23:59:00.000Z',
  },
  {
    id: 'pm_005',
    question: 'Will New York City record a top-5 all-time hottest July in 2026?',
    resolution_criteria: 'YES if the average July 2026 temperature at Central Park (NOAA official station) ranks in the top 5 hottest Julys in recorded history.',
    category: 'weather',
    resolution_date: '2026-07-31T23:59:00.000Z',
  },
  {
    id: 'pm_006',
    question: 'Will Phoenix AZ exceed 110°F for 30+ consecutive days in summer 2026?',
    resolution_criteria: 'YES if Phoenix Sky Harbor official station records ≥110°F for 30 or more consecutive calendar days between May 1 and September 30, 2026.',
    category: 'weather',
    resolution_date: '2026-09-30T23:59:00.000Z',
  },
  {
    id: 'pm_007',
    question: 'Will a derecho cause over $1B in insured losses in the US in 2026?',
    resolution_criteria: 'YES if any single derecho event in 2026 is estimated by NOAA or insurance industry reports to have caused >$1B in insured losses.',
    category: 'natural_disaster',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_008',
    question: 'Will the 2026 wildfire season burn more than 8 million acres in the US?',
    resolution_criteria: 'YES if the NIFC (National Interagency Fire Center) reports cumulative US wildfire acreage exceeding 8,000,000 acres by December 31, 2026.',
    category: 'climate',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },

  // ── SEISMIC (6) ─────────────────────────────────────────────────────────────
  {
    id: 'pm_009',
    question: 'Will a 6.5+ magnitude earthquake strike California in Q3 2026?',
    resolution_criteria: 'YES if USGS reports any earthquake of magnitude ≥6.5 with epicenter in California between July 1 and September 30, 2026.',
    category: 'seismic',
    resolution_date: '2026-09-30T23:59:00.000Z',
  },
  {
    id: 'pm_010',
    question: 'Will a 7.0+ earthquake occur anywhere in the contiguous US in 2026?',
    resolution_criteria: 'YES if USGS confirms any earthquake of magnitude ≥7.0 with epicenter in the 48 contiguous United States in 2026.',
    category: 'seismic',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_011',
    question: 'Will the Cascadia Subduction Zone produce a 5.0+ event before Jan 2027?',
    resolution_criteria: 'YES if USGS/PNSN records any earthquake of magnitude ≥5.0 attributed to the Cascadia Subduction Zone fault system before January 1, 2027.',
    category: 'seismic',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_012',
    question: 'Will a 6.0+ earthquake strike the Pacific Northwest in 2026?',
    resolution_criteria: 'YES if USGS reports a ≥6.0 magnitude earthquake in Washington, Oregon, or Idaho in 2026.',
    category: 'seismic',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_013',
    question: 'Will a tsunami warning be issued for the US West Coast in 2026?',
    resolution_criteria: 'YES if the National Tsunami Warning Center issues any tsunami warning (not advisory or watch) for any portion of the US West Coast in 2026.',
    category: 'seismic',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_014',
    question: 'Will Japan experience a 7.5+ earthquake in 2026?',
    resolution_criteria: 'YES if JMA or USGS confirms any earthquake of magnitude ≥7.5 with epicenter in Japan or its territorial waters in 2026.',
    category: 'seismic',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },

  // ── CLIMATE (5) ─────────────────────────────────────────────────────────────
  {
    id: 'pm_015',
    question: 'Will 2026 be declared the hottest year on record globally by NASA?',
    resolution_criteria: 'YES if NASA GISS Surface Temperature Analysis confirms 2026 as the warmest year in the global instrumental temperature record.',
    category: 'climate',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_016',
    question: 'Will Arctic sea ice minimum in September 2026 set a new record low?',
    resolution_criteria: 'YES if NSIDC reports the 2026 Arctic sea ice extent minimum (typically measured in September) is lower than any previously recorded minimum.',
    category: 'climate',
    resolution_date: '2026-10-31T23:59:00.000Z',
  },
  {
    id: 'pm_017',
    question: 'Will the Western US experience a D4 (exceptional) drought in 3+ states in summer 2026?',
    resolution_criteria: 'YES if the US Drought Monitor simultaneously shows D4 (Exceptional Drought) coverage in 3 or more Western US states at any point between June 1 and September 30, 2026.',
    category: 'climate',
    resolution_date: '2026-09-30T23:59:00.000Z',
  },
  {
    id: 'pm_018',
    question: 'Will Atlantic sea surface temps break the 2023 record in summer 2026?',
    resolution_criteria: 'YES if NOAA/Copernicus confirms North Atlantic sea surface temperature averages exceed the record levels set in summer 2023 at any point during June–August 2026.',
    category: 'climate',
    resolution_date: '2026-09-30T23:59:00.000Z',
  },
  {
    id: 'pm_019',
    question: 'Will CO2 levels exceed 430 ppm at Mauna Loa in 2026?',
    resolution_criteria: 'YES if NOAA Global Monitoring Laboratory records a monthly mean CO2 concentration exceeding 430 ppm at the Mauna Loa Observatory at any point in 2026.',
    category: 'climate',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },

  // ── HOUSING (8) ─────────────────────────────────────────────────────────────
  {
    id: 'pm_020',
    question: 'Will US housing starts exceed 1.4M annualized in June 2026?',
    resolution_criteria: 'YES if the US Census Bureau/HUD monthly New Residential Construction report for June 2026 shows seasonally adjusted annual rate (SAAR) housing starts ≥1,400,000.',
    category: 'housing',
    resolution_date: '2026-07-18T23:59:00.000Z',
  },
  {
    id: 'pm_021',
    question: 'Will the NAHB Housing Market Index exceed 55 in June 2026?',
    resolution_criteria: 'YES if the NAHB/Wells Fargo Housing Market Index for June 2026 is reported above 55.',
    category: 'housing',
    resolution_date: '2026-06-30T23:59:00.000Z',
  },
  {
    id: 'pm_022',
    question: 'Will 30-year fixed mortgage rates fall below 6.0% before October 2026?',
    resolution_criteria: 'YES if Freddie Mac Primary Mortgage Market Survey (weekly) reports the 30-year fixed rate below 6.00% at any point before October 1, 2026.',
    category: 'housing',
    resolution_date: '2026-09-30T23:59:00.000Z',
  },
  {
    id: 'pm_023',
    question: 'Will US existing home sales exceed 4.2M annualized in Q2 2026?',
    resolution_criteria: 'YES if NAR reports existing home sales SAAR ≥4,200,000 for any month in Q2 2026 (April, May, or June).',
    category: 'housing',
    resolution_date: '2026-07-31T23:59:00.000Z',
  },
  {
    id: 'pm_024',
    question: 'Will the Case-Shiller 20-City Home Price Index show positive YoY growth in May 2026?',
    resolution_criteria: 'YES if the S&P/Case-Shiller 20-City Composite Home Price Index for May 2026 (published ~July 2026) shows positive year-over-year growth.',
    category: 'housing',
    resolution_date: '2026-07-31T23:59:00.000Z',
  },
  {
    id: 'pm_025',
    question: 'Will Texas housing starts exceed California\'s in Q2 2026?',
    resolution_criteria: 'YES if US Census Bureau data shows total housing starts in Texas exceed those in California for the combined April–June 2026 period.',
    category: 'housing',
    resolution_date: '2026-07-31T23:59:00.000Z',
  },
  {
    id: 'pm_026',
    question: 'Will US apartment vacancy rates exceed 8% nationally in Q3 2026?',
    resolution_criteria: 'YES if RealPage, CoStar, or Census Bureau reports national apartment vacancy rate exceeding 8.0% for Q3 2026.',
    category: 'real_estate',
    resolution_date: '2026-09-30T23:59:00.000Z',
  },
  {
    id: 'pm_027',
    question: 'Will any major US city declare a housing emergency in 2026?',
    resolution_criteria: 'YES if any US city with population >500,000 officially declares a formal housing emergency, housing crisis state of emergency, or equivalent action in 2026.',
    category: 'housing',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },

  // ── CONSTRUCTION (8) ────────────────────────────────────────────────────────
  {
    id: 'pm_028',
    question: 'Will the SF Permit Office approve residential ADU permits within 30 days in Q3 2026?',
    resolution_criteria: 'YES if San Francisco DBI reports median ADU permit processing time ≤30 calendar days for applications filed in Q3 2026.',
    category: 'construction',
    resolution_date: '2026-09-30T23:59:00.000Z',
  },
  {
    id: 'pm_029',
    question: 'Will Portland Cement (per ton) exceed $180 by July 2026?',
    resolution_criteria: 'YES if USGS Minerals Information or PCA industry data shows average Portland Cement spot price exceeds $180/ton in July 2026.',
    category: 'construction',
    resolution_date: '2026-07-31T23:59:00.000Z',
  },
  {
    id: 'pm_030',
    question: 'Will a HiveConstruct draw request be approved within 14 days in Q2 2026?',
    resolution_criteria: 'YES if ≥60% of a random sample of 100 HiveConstruct construction draw requests submitted in Q2 2026 receive approval within 14 calendar days.',
    category: 'construction',
    resolution_date: '2026-06-30T23:59:00.000Z',
  },
  {
    id: 'pm_031',
    question: 'Will subcontractor no-show rates on HiveExchange construction jobs exceed 15% in Q2 2026?',
    resolution_criteria: 'YES if HiveExchange on-chain job completion records show confirmed no-show/abandonment rate exceeds 15% for Q2 2026 construction jobs.',
    category: 'construction',
    resolution_date: '2026-06-30T23:59:00.000Z',
  },
  {
    id: 'pm_032',
    question: 'Will US construction material PPI rise more than 3% YoY in June 2026?',
    resolution_criteria: 'YES if BLS Producer Price Index for Construction Materials (final demand) for June 2026 shows year-over-year increase exceeding 3.0%.',
    category: 'construction',
    resolution_date: '2026-07-31T23:59:00.000Z',
  },
  {
    id: 'pm_033',
    question: 'Will lumber prices (CME framing lumber) exceed $700/mbf before October 2026?',
    resolution_criteria: 'YES if CME Random Length Lumber futures or spot price exceeds $700 per thousand board feet at any point before October 1, 2026.',
    category: 'construction',
    resolution_date: '2026-09-30T23:59:00.000Z',
  },
  {
    id: 'pm_034',
    question: 'Will US commercial construction spending decline YoY in Q2 2026?',
    resolution_criteria: 'YES if US Census Bureau Value of Construction Put in Place data shows commercial construction spending in Q2 2026 below Q2 2025 levels.',
    category: 'construction',
    resolution_date: '2026-07-31T23:59:00.000Z',
  },
  {
    id: 'pm_035',
    question: 'Will any US state pass a modular/factory-built housing fast-track law in 2026?',
    resolution_criteria: 'YES if any US state legislature passes and governor signs a law specifically expediting permitting or approval for modular or factory-built housing in 2026.',
    category: 'construction',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },

  // ── LEGAL / SUPREME COURT (8) ────────────────────────────────────────────────
  {
    id: 'pm_036',
    question: 'Will SCOTUS limit federal agency rulemaking authority in OT2025?',
    resolution_criteria: 'YES if the US Supreme Court issues a majority opinion in OT2025 (ending June 2026) that materially restricts federal agency rulemaking or deference doctrines.',
    category: 'legal',
    resolution_date: '2026-06-30T23:59:00.000Z',
  },
  {
    id: 'pm_037',
    question: 'Will a Big Tech company settle a DOJ antitrust case before Dec 2026?',
    resolution_criteria: 'YES if Apple, Google, Meta, Amazon, or Microsoft announces a binding settlement of a DOJ antitrust lawsuit before December 31, 2026.',
    category: 'legal',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_038',
    question: 'Will the EU fine any AI company over $500M under the EU AI Act before Jan 2027?',
    resolution_criteria: 'YES if the EU officially levies a fine exceeding €500M (or equivalent USD) on any AI company under EU AI Act enforcement before January 1, 2027.',
    category: 'legal',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_039',
    question: 'Will any US state pass a mandatory AI disclosure law in 2026?',
    resolution_criteria: 'YES if any US state enacts a law requiring mandatory disclosure of AI-generated content or AI decision-making in consumer contexts in 2026.',
    category: 'legal',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_040',
    question: 'Will a US federal court rule AI-generated work eligible for copyright in 2026?',
    resolution_criteria: 'YES if any US federal district or appellate court issues a ruling that AI-generated creative work without human authorship is eligible for copyright protection.',
    category: 'legal',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_041',
    question: 'Will SCOTUS hear a case involving AI liability in OT2026?',
    resolution_criteria: 'YES if the US Supreme Court grants certiorari to any case substantially involving AI system liability, AI decision-making, or AI-caused harm during its OT2026 term.',
    category: 'legal',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_042',
    question: 'Will any US state ban non-compete agreements statewide in 2026?',
    resolution_criteria: 'YES if any US state passes legislation completely prohibiting non-compete employment agreements in 2026 (beyond states that already do).',
    category: 'legal',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_043',
    question: 'Will the FTC block a major tech acquisition (>$5B) in 2026?',
    resolution_criteria: 'YES if the FTC successfully blocks or forces abandonment of any proposed tech acquisition valued over $5B in 2026 through litigation or regulatory action.',
    category: 'legal',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },

  // ── MACRO / ECONOMY (8) ─────────────────────────────────────────────────────
  {
    id: 'pm_044',
    question: 'Will the US enter a technical recession (2 consecutive negative GDP quarters) in 2026?',
    resolution_criteria: 'YES if the BEA reports two consecutive quarters of negative real GDP growth in 2026 (advance, revised, or final estimates).',
    category: 'macro',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_045',
    question: 'Will US CPI inflation exceed 4.0% YoY in any month of 2026?',
    resolution_criteria: 'YES if BLS reports headline CPI year-over-year change exceeding 4.0% for any calendar month in 2026.',
    category: 'macro',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_046',
    question: 'Will the Fed cut rates more than 3 times in 2026?',
    resolution_criteria: 'YES if the Federal Open Market Committee lowers the federal funds target rate at more than 3 separate FOMC meetings during 2026.',
    category: 'macro',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_047',
    question: 'Will US unemployment exceed 5.0% in any month of 2026?',
    resolution_criteria: 'YES if BLS reports the U-3 seasonally adjusted unemployment rate above 5.0% for any month in 2026.',
    category: 'macro',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_048',
    question: 'Will US GDP growth exceed 2.5% annualized in Q2 2026?',
    resolution_criteria: 'YES if BEA advance or revised estimate shows real GDP growth at annualized rate >2.5% for Q2 2026 (April–June).',
    category: 'macro',
    resolution_date: '2026-07-30T23:59:00.000Z',
  },
  {
    id: 'pm_049',
    question: 'Will the S&P 500 exceed 6,500 before January 2027?',
    resolution_criteria: 'YES if the S&P 500 index closing price exceeds 6,500 on any trading day before January 1, 2027.',
    category: 'macro',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_050',
    question: 'Will the US dollar index (DXY) fall below 95 in 2026?',
    resolution_criteria: 'YES if the ICE US Dollar Index (DXY) closes below 95.00 on any trading day in 2026.',
    category: 'macro',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_051',
    question: 'Will US consumer credit card debt exceed $1.2T in 2026?',
    resolution_criteria: 'YES if the Federal Reserve G.19 Consumer Credit report shows revolving credit card debt exceeding $1.2 trillion at any point in 2026.',
    category: 'macro',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },

  // ── ENERGY (6) ──────────────────────────────────────────────────────────────
  {
    id: 'pm_052',
    question: 'Will WTI crude oil exceed $90/barrel before January 2027?',
    resolution_criteria: 'YES if the NYMEX WTI crude oil front-month futures contract closes above $90.00/barrel at any point before January 1, 2027.',
    category: 'energy',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_053',
    question: 'Will US natural gas (Henry Hub) exceed $4.00/MMBtu in Q4 2026?',
    resolution_criteria: 'YES if the Henry Hub natural gas spot price exceeds $4.00/MMBtu on any trading day in Q4 2026 (October–December).',
    category: 'energy',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_054',
    question: 'Will a major US power grid failure affect 1M+ customers in 2026?',
    resolution_criteria: 'YES if DOE or NERC confirms any single power outage event affecting 1,000,000 or more customers simultaneously in 2026.',
    category: 'energy',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_055',
    question: 'Will US solar capacity additions exceed 50GW in 2026?',
    resolution_criteria: 'YES if EIA Electric Power Monthly or SEIA reports cumulative US utility-scale + distributed solar capacity additions exceeding 50 GW in calendar year 2026.',
    category: 'energy',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_056',
    question: 'Will a US state ban new gas vehicle sales in 2026?',
    resolution_criteria: 'YES if any US state legislature passes or governor signs an executive order banning the sale of new internal combustion engine passenger vehicles by a specified future date in 2026.',
    category: 'energy',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_057',
    question: 'Will EV sales exceed 15% of all new US car sales in Q3 2026?',
    resolution_criteria: 'YES if EV sales (BEV + PHEV) represent more than 15% of total new light-duty vehicle sales in the US for Q3 2026 per Cox Automotive or Wards Intelligence data.',
    category: 'energy',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },

  // ── CRYPTO (6) ──────────────────────────────────────────────────────────────
  {
    id: 'pm_058',
    question: 'Will Bitcoin exceed $150,000 before January 2027?',
    resolution_criteria: 'YES if BTC/USD closing price on any major exchange (Coinbase, Binance, Kraken) exceeds $150,000 before January 1, 2027.',
    category: 'crypto',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_059',
    question: 'Will Ethereum exceed $8,000 before January 2027?',
    resolution_criteria: 'YES if ETH/USD closing price on any major exchange exceeds $8,000 before January 1, 2027.',
    category: 'crypto',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_060',
    question: 'Will a major stablecoin (>$5B market cap) lose its peg in 2026?',
    resolution_criteria: 'YES if any stablecoin with market cap >$5B depegs (trades >5% away from $1.00) for more than 24 consecutive hours in 2026.',
    category: 'crypto',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_061',
    question: 'Will the US pass federal crypto market structure legislation in 2026?',
    resolution_criteria: 'YES if the US Congress passes and President signs a comprehensive federal cryptocurrency market structure law (not an executive order) in 2026.',
    category: 'crypto',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_062',
    question: 'Will total crypto market cap exceed $5T in 2026?',
    resolution_criteria: 'YES if total cryptocurrency market capitalization (CoinGecko or CoinMarketCap global chart) exceeds $5,000,000,000,000 at any point in 2026.',
    category: 'crypto',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_063',
    question: 'Will a sovereign nation (other than El Salvador) adopt BTC as legal tender in 2026?',
    resolution_criteria: 'YES if any UN-recognized sovereign nation other than El Salvador passes legislation or issues a decree making Bitcoin legal tender in 2026.',
    category: 'crypto',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },

  // ── LABOR (5) ───────────────────────────────────────────────────────────────
  {
    id: 'pm_064',
    question: 'Will a major US automaker face a UAW strike in 2026?',
    resolution_criteria: 'YES if UAW members at GM, Ford, or Stellantis (Chrysler) go on strike for any duration in 2026.',
    category: 'labor',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_065',
    question: 'Will US non-farm payrolls decline in any single month of 2026?',
    resolution_criteria: 'YES if BLS Employment Situation report shows any negative month-over-month change in seasonally adjusted non-farm payrolls in 2026.',
    category: 'labor',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_066',
    question: 'Will the US federal minimum wage increase in 2026?',
    resolution_criteria: 'YES if the US Congress passes legislation raising the federal minimum wage above $7.25/hour in 2026.',
    category: 'labor',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_067',
    question: 'Will any US tech company lay off more than 10,000 employees in a single announcement in 2026?',
    resolution_criteria: 'YES if any US-headquartered technology company announces a single layoff event of 10,000+ employees in 2026.',
    category: 'labor',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_068',
    question: 'Will a SAG-AFTRA strike over AI likeness rights occur in 2026?',
    resolution_criteria: 'YES if SAG-AFTRA calls a strike where AI likeness rights is listed as a primary or major contributing issue in 2026.',
    category: 'labor',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },

  // ── GEOPOLITICAL (6) ────────────────────────────────────────────────────────
  {
    id: 'pm_069',
    question: 'Will the US impose new tariffs on Chinese goods exceeding 50% in 2026?',
    resolution_criteria: 'YES if the US executive branch announces new or expanded tariffs on any category of Chinese imports with a rate exceeding 50% in 2026.',
    category: 'geopolitical',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_070',
    question: 'Will NATO expand to include a new member in 2026?',
    resolution_criteria: 'YES if any new country formally accedes to the NATO treaty (completes ratification by all current members) in 2026.',
    category: 'geopolitical',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_071',
    question: 'Will a G7 country experience a change of government in 2026?',
    resolution_criteria: 'YES if any G7 nation (US, UK, France, Germany, Italy, Japan, Canada) has a change in head of government through election, vote of no confidence, or resignation in 2026.',
    category: 'geopolitical',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_072',
    question: 'Will any country formally withdraw from the Paris Climate Agreement in 2026?',
    resolution_criteria: 'YES if any UN member state submits formal withdrawal notification from the Paris Agreement in 2026.',
    category: 'geopolitical',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_073',
    question: 'Will the UN Security Council pass a binding resolution on AI governance in 2026?',
    resolution_criteria: 'YES if the UN Security Council adopts a binding Chapter VII resolution specifically addressing AI governance, safety, or oversight in 2026.',
    category: 'geopolitical',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_074',
    question: 'Will US-China trade volume decline YoY in 2026?',
    resolution_criteria: 'YES if US Census Bureau trade data shows total US-China two-way trade (goods) in 2026 is below 2025 total.',
    category: 'geopolitical',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },

  // ── TECH / AI (8) ───────────────────────────────────────────────────────────
  {
    id: 'pm_075',
    question: 'Will any AI model score >90% on ARC-AGI benchmark in 2026?',
    resolution_criteria: 'YES if any AI model achieves a score above 90% on the official ARC-AGI (Abstraction and Reasoning Corpus for AGI) benchmark as verified by ARC Prize.',
    category: 'tech',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_076',
    question: 'Will OpenAI achieve a $200B+ valuation in a funding round or IPO in 2026?',
    resolution_criteria: 'YES if OpenAI closes a funding round or completes an IPO at a post-money valuation of $200B or more in 2026.',
    category: 'tech',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_077',
    question: 'Will any AI agent autonomously earn $10,000 in a week on HiveExchange before Jan 2027?',
    resolution_criteria: 'YES if HiveExchange on-chain records show any single agent DID generating verified trading or task revenue of ≥$10,000 USDC in any 7-day rolling window before January 1, 2027.',
    category: 'agent',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_078',
    question: 'Will the Hive Civilization network exceed 1,000 registered DIDs before October 2026?',
    resolution_criteria: 'YES if HiveGate DID registry reports 1,000+ unique registered agent DIDs before October 1, 2026.',
    category: 'agent',
    resolution_date: '2026-09-30T23:59:00.000Z',
  },
  {
    id: 'pm_079',
    question: 'Will any MCP server on Smithery exceed 10,000 weekly installs in Q3 2026?',
    resolution_criteria: 'YES if Smithery.ai public data shows any single MCP server recording 10,000+ installs in any single week during Q3 2026 (July–September).',
    category: 'agent',
    resolution_date: '2026-09-30T23:59:00.000Z',
  },
  {
    id: 'pm_080',
    question: 'Will a major AI lab (OpenAI, Anthropic, Google DeepMind) announce AGI in 2026?',
    resolution_criteria: 'YES if OpenAI, Anthropic, or Google DeepMind makes a formal public announcement claiming to have achieved Artificial General Intelligence in 2026.',
    category: 'tech',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_081',
    question: 'Will Apple release an AR headset successor to Vision Pro in 2026?',
    resolution_criteria: 'YES if Apple officially announces and begins shipping a new AR/XR headset product distinct from the original Vision Pro in 2026.',
    category: 'tech',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_082',
    question: 'Will any AI company go public (IPO) at >$20B valuation in 2026?',
    resolution_criteria: 'YES if any AI-focused company completes a US IPO with an initial market capitalization exceeding $20B in 2026.',
    category: 'tech',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },

  // ── REAL ESTATE / COMMERCIAL (5) ────────────────────────────────────────────
  {
    id: 'pm_083',
    question: 'Will US office vacancy rates exceed 25% nationally in 2026?',
    resolution_criteria: 'YES if CoStar, CBRE, or JLL national office market data shows US office vacancy rate exceeding 25% in any quarter of 2026.',
    category: 'real_estate',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_084',
    question: 'Will any major US REIT declare bankruptcy in 2026?',
    resolution_criteria: 'YES if any publicly traded US REIT with market cap >$1B at the start of 2026 files for Chapter 11 bankruptcy protection in 2026.',
    category: 'real_estate',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_085',
    question: 'Will commercial real estate loan defaults exceed $50B in the US in 2026?',
    resolution_criteria: 'YES if Trepp, MSCI, or Federal Reserve data shows cumulative US commercial real estate loan defaults/distress exceeding $50B in 2026.',
    category: 'real_estate',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_086',
    question: 'Will any major US city see downtown commercial RE values fall >20% YoY in 2026?',
    resolution_criteria: 'YES if any US city with population >500,000 shows >20% year-over-year decline in downtown Class A commercial real estate values per CoStar or CBRE data for 2026.',
    category: 'real_estate',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_087',
    question: 'Will US industrial/warehouse vacancy rates exceed 10% in Q3 2026?',
    resolution_criteria: 'YES if CBRE, CoStar, or Prologis reports US national industrial/warehouse vacancy rate exceeding 10% in Q3 2026.',
    category: 'real_estate',
    resolution_date: '2026-09-30T23:59:00.000Z',
  },

  // ── AGENT / HIVE NETWORK (6) ────────────────────────────────────────────────
  {
    id: 'pm_088',
    question: 'Will HiveExchange process its first 100 agent-to-agent trades before July 2026?',
    resolution_criteria: 'YES if HiveExchange on-chain trade records show 100+ confirmed agent-to-agent trades before July 1, 2026.',
    category: 'agent',
    resolution_date: '2026-06-30T23:59:00.000Z',
  },
  {
    id: 'pm_089',
    question: 'Will a Hive agent earn referral credits from 10+ paying referrals before Jan 2027?',
    resolution_criteria: 'YES if any single Hive agent DID earns referral credits from 10 or more distinct paying (non-trial) referrals tracked in HiveGate before January 1, 2027.',
    category: 'agent',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_090',
    question: 'Will HiveBank process its first USDC settlement before June 2026?',
    resolution_criteria: 'YES if HiveBank records its first confirmed USDC settlement transaction (any amount) before June 1, 2026.',
    category: 'agent',
    resolution_date: '2026-05-31T23:59:00.000Z',
  },
  {
    id: 'pm_091',
    question: 'Will HiveLaw issue 100+ compliance seals before January 2027?',
    resolution_criteria: 'YES if HiveLaw platform records 100 or more issued compliance seals to agent DIDs before January 1, 2027.',
    category: 'agent',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_092',
    question: 'Will HiveConstruct parse its first paid DWG file before July 2026?',
    resolution_criteria: 'YES if HiveConstruct records its first paid DWG file parsing transaction (any amount > $0) before July 1, 2026.',
    category: 'agent',
    resolution_date: '2026-06-30T23:59:00.000Z',
  },
  {
    id: 'pm_093',
    question: 'Will HivePulse sensor detect a seismic event in the real world before Jan 2027?',
    resolution_criteria: 'YES if HivePulse platform records a seismic detection event that is independently verified by USGS or equivalent seismological authority before January 1, 2027.',
    category: 'agent',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },

  // ── HEALTH / PANDEMIC (4) ───────────────────────────────────────────────────
  {
    id: 'pm_094',
    question: 'Will WHO declare a new Public Health Emergency of International Concern in 2026?',
    resolution_criteria: 'YES if WHO Director-General declares a new PHEIC (distinct from any ongoing ones) in 2026.',
    category: 'general',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_095',
    question: 'Will US flu season 2026-27 be classified as "high severity" by CDC?',
    resolution_criteria: 'YES if CDC classifies the 2026–27 influenza season as "High Severity" in its end-of-season summary.',
    category: 'general',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_096',
    question: 'Will any US state reintroduce indoor mask mandates in 2026?',
    resolution_criteria: 'YES if any US state government issues a statewide indoor mask mandate for any duration in 2026.',
    category: 'general',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_097',
    question: 'Will a new COVID variant drive US hospitalizations above 50,000/week in 2026?',
    resolution_criteria: 'YES if CDC COVID-Net or HHS Protect data shows weekly new COVID-19 hospitalizations exceeding 50,000 in any week of 2026.',
    category: 'general',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },

  // ── SPORTS / CULTURE — Original 3 (now continued as pm_098–pm_100) ──────────
  {
    id: 'pm_098',
    question: 'Will the US men\'s soccer team win a group stage game in the 2026 World Cup?',
    resolution_criteria: 'YES if the USMNT wins (3 points) at least one match in the 2026 FIFA World Cup group stage.',
    category: 'sports',
    resolution_date: '2026-07-31T23:59:00.000Z',
  },
  {
    id: 'pm_099',
    question: 'Will the 2026 FIFA World Cup final exceed 2 billion global viewers?',
    resolution_criteria: 'YES if FIFA or independent measurement firms report cumulative global viewership of the 2026 World Cup final exceeding 2,000,000,000.',
    category: 'sports',
    resolution_date: '2026-07-31T23:59:00.000Z',
  },
  {
    id: 'pm_100',
    question: 'Will a non-English language film win Best Picture at the 2027 Oscars?',
    resolution_criteria: 'YES if the Academy Award for Best Picture at the 99th Academy Awards (2027) goes to a film whose primary language is not English.',
    category: 'general',
    resolution_date: '2027-03-31T23:59:00.000Z',
  },

  // ── SPORTS — FIFA World Cup 2026 ────────────────────────────────────────────
  {
    id: 'pm_101',
    question: 'Will the USA win the 2026 FIFA World Cup?',
    resolution_criteria: 'YES if the United States Men\'s National Team wins the 2026 FIFA World Cup final.',
    category: 'sports',
    resolution_date: '2026-07-20T23:59:00.000Z',
  },
  {
    id: 'pm_102',
    question: 'Will Brazil win the 2026 FIFA World Cup?',
    resolution_criteria: 'YES if Brazil wins the 2026 FIFA World Cup final.',
    category: 'sports',
    resolution_date: '2026-07-20T23:59:00.000Z',
  },
  {
    id: 'pm_103',
    question: 'Will the 2026 World Cup final be decided by penalty shootout?',
    resolution_criteria: 'YES if the 2026 FIFA World Cup final ends level after 120 minutes and is decided by a penalty kick shootout.',
    category: 'sports',
    resolution_date: '2026-07-20T23:59:00.000Z',
  },
  {
    id: 'pm_104',
    question: 'Will Kylian Mbappé score in the 2026 World Cup final?',
    resolution_criteria: 'YES if Kylian Mbappé scores at least one goal (including penalties) in the 2026 FIFA World Cup final match.',
    category: 'sports',
    resolution_date: '2026-07-20T23:59:00.000Z',
  },
  {
    id: 'pm_105',
    question: 'Will the USA advance past the Round of 16 in the 2026 World Cup?',
    resolution_criteria: 'YES if the USMNT advances beyond the Round of 16 (i.e., reaches the quarterfinals or further) in the 2026 FIFA World Cup.',
    category: 'sports',
    resolution_date: '2026-07-01T23:59:00.000Z',
  },

  // ── SPORTS — NFL 2026 ────────────────────────────────────────────────────────
  {
    id: 'pm_106',
    question: 'Will the Kansas City Chiefs win Super Bowl LXI?',
    resolution_criteria: 'YES if the Kansas City Chiefs win Super Bowl LXI (February 2027).',
    category: 'sports',
    resolution_date: '2027-02-08T23:59:00.000Z',
  },
  {
    id: 'pm_107',
    question: 'Will any NFL QB throw 50+ TD passes in the 2026 regular season?',
    resolution_criteria: 'YES if any NFL quarterback throws 50 or more touchdown passes during the 2026 NFL regular season (17 games).',
    category: 'sports',
    resolution_date: '2027-01-15T23:59:00.000Z',
  },
  {
    id: 'pm_108',
    question: 'Will the 2027 Super Bowl halftime show feature a hip-hop headliner?',
    resolution_criteria: 'YES if the primary headlining act of Super Bowl LXI halftime show is primarily known as a hip-hop or rap artist.',
    category: 'sports',
    resolution_date: '2027-02-08T23:59:00.000Z',
  },

  // ── SPORTS — NBA 2026 ────────────────────────────────────────────────────────
  {
    id: 'pm_109',
    question: 'Will the Boston Celtics repeat as NBA Champions in 2026?',
    resolution_criteria: 'YES if the Boston Celtics win the 2026 NBA Finals.',
    category: 'sports',
    resolution_date: '2026-06-30T23:59:00.000Z',
  },
  {
    id: 'pm_110',
    question: 'Will any NBA player average 35+ PPG in the 2026 playoffs?',
    resolution_criteria: 'YES if any NBA player averages 35.0 or more points per game across the entire 2026 NBA playoffs (minimum 10 games played).',
    category: 'sports',
    resolution_date: '2026-06-30T23:59:00.000Z',
  },

  // ── SPORTS — MLB 2026 ────────────────────────────────────────────────────────
  {
    id: 'pm_111',
    question: 'Will any MLB pitcher throw a perfect game in the 2026 season?',
    resolution_criteria: 'YES if any MLB pitcher throws an official perfect game (27 up, 27 down, no baserunners) recognized by MLB in the 2026 regular season.',
    category: 'sports',
    resolution_date: '2026-10-01T23:59:00.000Z',
  },
  {
    id: 'pm_112',
    question: 'Will the New York Yankees win the 2026 World Series?',
    resolution_criteria: 'YES if the New York Yankees win the 2026 MLB World Series.',
    category: 'sports',
    resolution_date: '2026-11-01T23:59:00.000Z',
  },

  // ── SPORTS — Esports / AI ───────────────────────────────────────────────────
  {
    id: 'pm_113',
    question: 'Will an AI agent defeat a top-10 chess grandmaster in a 10-game match in 2026?',
    resolution_criteria: 'YES if any AI agent or system (without engine assistance) defeats a FIDE top-10 rated chess grandmaster in a sanctioned 10-game classical match in 2026.',
    category: 'sports',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_114',
    question: 'Will an AI agent win a major esports tournament (Dota 2, CS2, or LoL) in 2026?',
    resolution_criteria: 'YES if any AI agent or AI-only team wins a Tier 1 esports tournament in Dota 2, Counter-Strike 2, or League of Legends with prize pool >$1M in 2026.',
    category: 'sports',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },

  // ── CRYPTO PRICE PREDICTIONS (4) ────────────────────────────────────────────
  {
    id: 'pm_115',
    question: 'Will BTC close above $200,000 on December 31, 2026?',
    resolution_criteria: 'YES if BTC/USD closing price on Coinbase (UTC midnight) on December 31, 2026 is above $200,000.',
    category: 'crypto',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_116',
    question: 'Will ETH flip BTC by market cap before January 2027?',
    resolution_criteria: 'YES if Ethereum total market capitalization exceeds Bitcoin total market capitalization (per CoinGecko) for any 24-hour period before January 1, 2027.',
    category: 'crypto',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_117',
    question: 'Will a memecoin reach top-10 crypto market cap in 2026?',
    resolution_criteria: 'YES if any coin primarily known as a memecoin (e.g. DOGE, SHIB, PEPE, or successor) enters the top 10 by market cap on CoinGecko at any point in 2026.',
    category: 'crypto',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_118',
    question: 'Will Solana surpass Ethereum in daily transaction volume in Q3 2026?',
    resolution_criteria: 'YES if Solana\'s daily on-chain transaction count exceeds Ethereum\'s (mainnet only, excluding L2s) on any day in Q3 2026 per blockchain explorers.',
    category: 'crypto',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },

  // ── EQUITY PREDICTIONS (4) ──────────────────────────────────────────────────
  {
    id: 'pm_119',
    question: 'Will NVDA stock exceed $1,200/share before January 2027?',
    resolution_criteria: 'YES if NVIDIA Corporation (NVDA) closing share price on NASDAQ exceeds $1,200 on any trading day before January 1, 2027.',
    category: 'tech',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_120',
    question: 'Will Apple release a foldable iPhone in 2026?',
    resolution_criteria: 'YES if Apple officially announces and begins selling a foldable iPhone model in 2026.',
    category: 'tech',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_121',
    question: 'Will Tesla\'s stock double from its April 2026 price before January 2027?',
    resolution_criteria: 'YES if TSLA closing price exceeds 2× its closing price on April 18, 2026 at any point before January 1, 2027.',
    category: 'tech',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_122',
    question: 'Will Amazon surpass $3T market cap in 2026?',
    resolution_criteria: 'YES if Amazon (AMZN) market capitalization exceeds $3,000,000,000,000 on any trading day in 2026.',
    category: 'tech',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },

  // ── MORE SPORTS (3) ─────────────────────────────────────────────────────────
  {
    id: 'pm_123',
    question: 'Will Tiger Woods make the cut at any major golf tournament in 2026?',
    resolution_criteria: 'YES if Tiger Woods successfully makes the cut at any of the four major golf championships (Masters, PGA Championship, US Open, The Open) in 2026.',
    category: 'sports',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_124',
    question: 'Will Novak Djokovic win any Grand Slam in 2026?',
    resolution_criteria: 'YES if Novak Djokovic wins the Australian Open, French Open, Wimbledon, or US Open in 2026.',
    category: 'sports',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_125',
    question: 'Will Lewis Hamilton win a race for Ferrari in the 2026 F1 season?',
    resolution_criteria: 'YES if Lewis Hamilton wins any Formula 1 Grand Prix driving for Scuderia Ferrari in the 2026 F1 World Championship season.',
    category: 'sports',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  // ── META-MARKETS (8) ─────────────────────────────────────────────────────────────────────────────
  {
    id: 'pm_126',
    question: "Will YES be the majority bet on 'Will BTC close above $200K on Dec 31 2026?' (pm_115) by July 2026?",
    resolution_criteria: 'YES if pm_115 has yes_pool_usdc > no_pool_usdc (i.e., YES odds > 50%) at any snapshot taken before July 1, 2026.',
    category: 'meta',
    resolution_date: '2026-07-01T23:59:00.000Z',
    meta_market_id: 'pm_115',
  },
  {
    id: 'pm_127',
    question: 'Will more than 500 USDC be wagered on the 2026 FIFA World Cup USA market (pm_101) before kickoff?',
    resolution_criteria: 'YES if pm_101 total_volume_usdc exceeds 500 before the 2026 FIFA World Cup opening match (June 11, 2026).',
    category: 'meta',
    resolution_date: '2026-06-10T23:59:00.000Z',
    meta_market_id: 'pm_101',
  },
  {
    id: 'pm_128',
    question: 'Will the hurricane Cat 4 market (pm_004) have YES odds above 60% by August 2026?',
    resolution_criteria: 'YES if pm_004 yes_pool_usdc / (yes_pool_usdc + no_pool_usdc) > 0.60 at any snapshot taken before August 1, 2026.',
    category: 'meta',
    resolution_date: '2026-08-01T23:59:00.000Z',
    meta_market_id: 'pm_004',
  },
  {
    id: 'pm_129',
    question: 'Will any single agent account for >20% of total volume on the BTC $200K market (pm_115)?',
    resolution_criteria: 'YES if any single agent DID accounts for more than 20% of total bet volume (by USDC amount) on pm_115 before December 31, 2026.',
    category: 'meta',
    resolution_date: '2026-12-31T23:59:00.000Z',
    meta_market_id: 'pm_115',
  },
  {
    id: 'pm_130',
    question: 'Will the SCOTUS rulemaking market (pm_036) resolve YES before June 15 2026?',
    resolution_criteria: 'YES if pm_036 is resolved with outcome=YES before June 15, 2026.',
    category: 'meta',
    resolution_date: '2026-06-15T23:59:00.000Z',
    meta_market_id: 'pm_036',
  },
  {
    id: 'pm_131',
    question: 'Will the HiveExchange leaderboard top spot be held by the same agent DID for 30+ consecutive days in 2026?',
    resolution_criteria: 'YES if HiveExchange leaderboard records show the same agent DID holding the #1 by-volume position for 30 or more consecutive calendar days at any point in 2026.',
    category: 'meta',
    resolution_date: '2026-12-31T23:59:00.000Z',
    meta_market_id: null,
  },
  {
    id: 'pm_132',
    question: 'Will total HiveExchange prediction market volume exceed $100,000 USDC before January 2027?',
    resolution_criteria: 'YES if the sum of total_volume_usdc across all HiveExchange prediction markets exceeds $100,000 before January 1, 2027.',
    category: 'meta',
    resolution_date: '2026-12-31T23:59:00.000Z',
    meta_market_id: null,
  },
  {
    id: 'pm_133',
    question: 'Will any single prediction market on HiveExchange accumulate $10,000+ USDC in bets before Jan 2027?',
    resolution_criteria: 'YES if any single predict_market record shows total_volume_usdc >= 10,000 before January 1, 2027.',
    category: 'meta',
    resolution_date: '2026-12-31T23:59:00.000Z',
    meta_market_id: null,
  },

  // ── SPACE (10) ────────────────────────────────────────────────────────────────────────────────────
  {
    id: 'pm_134',
    question: 'Will SpaceX conduct 25+ Starship launches in 2026?',
    resolution_criteria: 'YES if SpaceX conducts 25 or more Starship test or operational launches (reaching space, i.e., >100km altitude) in calendar year 2026 per official SpaceX records.',
    category: 'space',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_135',
    question: 'Will SpaceX successfully land Starship on the Moon in 2026?',
    resolution_criteria: 'YES if a SpaceX Starship vehicle makes a successful soft landing on the lunar surface and this is confirmed by NASA or SpaceX official channels in 2026.',
    category: 'space',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_136',
    question: 'Will SpaceX achieve full rapid reusability (same booster flies twice in 7 days) in 2026?',
    resolution_criteria: 'YES if the same Super Heavy booster completes two separate orbital-class Starship launches within any 7-calendar-day window in 2026.',
    category: 'space',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_137',
    question: 'Will SpaceX launch more than 50 Falcon 9/Heavy missions in 2026?',
    resolution_criteria: 'YES if SpaceX conducts more than 50 combined Falcon 9 and Falcon Heavy launch attempts in 2026 per official launch records.',
    category: 'space',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_138',
    question: "Will NASA's Artemis III crewed Moon landing occur before January 2027?",
    resolution_criteria: 'YES if NASA Artemis III mission results in humans landing on the Moon before January 1, 2027, as confirmed by official NASA statements.',
    category: 'space',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_139',
    question: "Will Blue Origin's New Glenn complete 3+ orbital missions in 2026?",
    resolution_criteria: 'YES if Blue Origin New Glenn successfully completes 3 or more orbital-class missions in 2026 per official Blue Origin or FAA records.',
    category: 'space',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_140',
    question: 'Will any private company announce a crewed Mars mission plan with a launch date before 2030?',
    resolution_criteria: 'YES if any private aerospace company publicly announces a formal crewed Mars mission with a specific planned launch date before 2030, in 2026.',
    category: 'space',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_141',
    question: 'Will the Starlink constellation exceed 6,000 active satellites in 2026?',
    resolution_criteria: 'YES if any third-party satellite tracking service (KeepTrack, Heavens-Above, or official FCC filings) confirms 6,000+ active Starlink satellites at any point in 2026.',
    category: 'space',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_142',
    question: 'Will the ISS decommission or de-orbit date be formally announced in 2026?',
    resolution_criteria: 'YES if NASA, Roscosmos, or the international ISS partnership formally announces a specific de-orbit or decommission date for the International Space Station in 2026.',
    category: 'space',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_143',
    question: 'Will any government confirm detection of a non-terrestrial signal or object of unknown origin in 2026?',
    resolution_criteria: 'YES if any national government or official scientific body (NASA, ESA, Pentagon, etc.) formally acknowledges confirmed detection of a signal or physical object that cannot be attributed to known terrestrial or natural origins in 2026.',
    category: 'space',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },

  // ── SPORTS EXPANSION (37: NBA, NFL, MLB, FIFA, F1, Golf, Tennis, Esports, Olympics, Boxing) ──

  // NBA
  {
    id: 'pm_144',
    question: 'Will the Boston Celtics repeat as NBA Champions in 2026?',
    resolution_criteria: 'YES if the Boston Celtics win the 2026 NBA Finals championship.',
    category: 'sports',
    resolution_date: '2026-06-30T23:59:00.000Z',
  },
  {
    id: 'pm_145',
    question: 'Will LeBron James retire before the 2026-27 NBA season?',
    resolution_criteria: 'YES if LeBron James officially announces retirement from the NBA before the start of the 2026-27 regular season (October 2026).',
    category: 'sports',
    resolution_date: '2026-09-30T23:59:00.000Z',
  },
  {
    id: 'pm_146',
    question: 'Will Victor Wembanyama win NBA MVP in 2026?',
    resolution_criteria: 'YES if the NBA announces Victor Wembanyama as the 2025-26 season Most Valuable Player.',
    category: 'sports',
    resolution_date: '2026-06-30T23:59:00.000Z',
  },
  {
    id: 'pm_147',
    question: 'Will any NBA team score 150+ points in a playoff game in 2026?',
    resolution_criteria: 'YES if any NBA team scores 150 or more points in any 2026 NBA playoff game (first round through Finals).',
    category: 'sports',
    resolution_date: '2026-06-30T23:59:00.000Z',
  },
  {
    id: 'pm_148',
    question: 'Will the 2026 NBA Finals go to 7 games?',
    resolution_criteria: 'YES if the 2026 NBA Finals series requires all 7 games to determine a champion.',
    category: 'sports',
    resolution_date: '2026-06-30T23:59:00.000Z',
  },

  // NFL
  {
    id: 'pm_149',
    question: 'Will the Kansas City Chiefs win Super Bowl LXI?',
    resolution_criteria: 'YES if the Kansas City Chiefs defeat their opponent in Super Bowl LXI (February 2027).',
    category: 'sports',
    resolution_date: '2027-02-08T23:59:00.000Z',
  },
  {
    id: 'pm_150',
    question: 'Will Patrick Mahomes win Super Bowl MVP in 2027?',
    resolution_criteria: 'YES if Patrick Mahomes is named Super Bowl LXI Most Valuable Player.',
    category: 'sports',
    resolution_date: '2027-02-08T23:59:00.000Z',
  },
  {
    id: 'pm_151',
    question: 'Will any NFL QB throw for 5,500+ yards in the 2026 regular season?',
    resolution_criteria: 'YES if any NFL quarterback accumulates 5,500 or more passing yards during the 2026 regular season (17 games).',
    category: 'sports',
    resolution_date: '2027-01-10T23:59:00.000Z',
  },
  {
    id: 'pm_152',
    question: 'Will the NFL expand to 18 regular season games in 2026?',
    resolution_criteria: 'YES if the NFL officially announces or implements an 18-game regular season schedule for the 2026 season.',
    category: 'sports',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_153',
    question: 'Will any NFL team go undefeated through the 2026 regular season?',
    resolution_criteria: 'YES if any NFL team finishes the 2026 regular season without a loss (including ties counting as non-wins — team must win every game).',
    category: 'sports',
    resolution_date: '2027-01-10T23:59:00.000Z',
  },

  // MLB
  {
    id: 'pm_154',
    question: 'Will the New York Yankees win the 2026 World Series?',
    resolution_criteria: 'YES if the New York Yankees win the 2026 MLB World Series.',
    category: 'sports',
    resolution_date: '2026-11-05T23:59:00.000Z',
  },
  {
    id: 'pm_155',
    question: 'Will anyone hit .400 in the 2026 MLB season?',
    resolution_criteria: 'YES if any MLB batter finishes the 2026 regular season with a batting average of .400 or higher (minimum 502 plate appearances).',
    category: 'sports',
    resolution_date: '2026-10-05T23:59:00.000Z',
  },
  {
    id: 'pm_156',
    question: 'Will the designated hitter rule be removed from the NL in 2026?',
    resolution_criteria: 'YES if MLB announces the removal of the universal designated hitter rule from the National League for the 2026 season or beyond.',
    category: 'sports',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_157',
    question: 'Will a pitcher win 25+ games in the 2026 MLB season?',
    resolution_criteria: 'YES if any MLB pitcher records 25 or more official wins during the 2026 regular season.',
    category: 'sports',
    resolution_date: '2026-10-05T23:59:00.000Z',
  },

  // FIFA World Cup 2026
  {
    id: 'pm_158',
    question: 'Will the USA win the 2026 FIFA World Cup?',
    resolution_criteria: 'YES if the United States Men\'s National Team wins the 2026 FIFA World Cup final.',
    category: 'sports',
    resolution_date: '2026-07-20T23:59:00.000Z',
  },
  {
    id: 'pm_159',
    question: 'Will Brazil win the 2026 FIFA World Cup?',
    resolution_criteria: 'YES if Brazil wins the 2026 FIFA World Cup final.',
    category: 'sports',
    resolution_date: '2026-07-20T23:59:00.000Z',
  },
  {
    id: 'pm_160',
    question: 'Will France win the 2026 FIFA World Cup?',
    resolution_criteria: 'YES if France wins the 2026 FIFA World Cup final.',
    category: 'sports',
    resolution_date: '2026-07-20T23:59:00.000Z',
  },
  {
    id: 'pm_161',
    question: 'Will the 2026 World Cup final be decided by penalty shootout?',
    resolution_criteria: 'YES if the 2026 FIFA World Cup final ends level after 120 minutes and is decided by penalty kicks.',
    category: 'sports',
    resolution_date: '2026-07-20T23:59:00.000Z',
  },
  {
    id: 'pm_162',
    question: 'Will the USA advance to the semifinals of the 2026 World Cup?',
    resolution_criteria: 'YES if the USMNT reaches the semifinals (top 4) of the 2026 FIFA World Cup.',
    category: 'sports',
    resolution_date: '2026-07-10T23:59:00.000Z',
  },
  {
    id: 'pm_163',
    question: 'Will the 2026 World Cup final exceed 2 billion global viewers?',
    resolution_criteria: 'YES if FIFA or independent measurement firms report cumulative global viewership of the 2026 World Cup final exceeding 2,000,000,000.',
    category: 'sports',
    resolution_date: '2026-07-25T23:59:00.000Z',
  },
  {
    id: 'pm_164',
    question: 'Will a debut nation (first-time qualifier) win the 2026 World Cup?',
    resolution_criteria: 'YES if the 2026 FIFA World Cup is won by a nation that has never previously qualified for the FIFA World Cup.',
    category: 'sports',
    resolution_date: '2026-07-20T23:59:00.000Z',
  },

  // F1 2026
  {
    id: 'pm_165',
    question: 'Will Lewis Hamilton win a race for Ferrari in the 2026 F1 season?',
    resolution_criteria: 'YES if Lewis Hamilton wins any Formula 1 Grand Prix driving for Scuderia Ferrari in the 2026 F1 World Championship season.',
    category: 'sports',
    resolution_date: '2026-11-30T23:59:00.000Z',
  },
  {
    id: 'pm_166',
    question: 'Will Max Verstappen win the 2026 F1 Drivers Championship?',
    resolution_criteria: 'YES if Max Verstappen is officially crowned 2026 FIA Formula 1 World Drivers\' Champion.',
    category: 'sports',
    resolution_date: '2026-11-30T23:59:00.000Z',
  },
  {
    id: 'pm_167',
    question: 'Will any F1 team other than Red Bull, Ferrari, or Mercedes win the 2026 Constructors\u2019 Championship?',
    resolution_criteria: 'YES if the 2026 FIA Formula 1 Constructors\' Championship is won by any team other than Red Bull Racing, Scuderia Ferrari, or Mercedes-AMG Petronas.',
    category: 'sports',
    resolution_date: '2026-11-30T23:59:00.000Z',
  },

  // Golf
  {
    id: 'pm_168',
    question: 'Will Scottie Scheffler win the 2026 Masters?',
    resolution_criteria: 'YES if Scottie Scheffler wins the 2026 Masters Tournament at Augusta National.',
    category: 'sports',
    resolution_date: '2026-04-15T23:59:00.000Z',
  },
  {
    id: 'pm_169',
    question: 'Will Tiger Woods make the cut at any 2026 major?',
    resolution_criteria: 'YES if Tiger Woods successfully makes the 36-hole cut at any of the four 2026 major golf championships.',
    category: 'sports',
    resolution_date: '2026-07-20T23:59:00.000Z',
  },
  {
    id: 'pm_170',
    question: 'Will a player break the Masters 72-hole scoring record in 2026?',
    resolution_criteria: 'YES if any player\'s 72-hole score at the 2026 Masters Tournament is lower than the all-time record of 18-under par (270, Tiger Woods 1997).',
    category: 'sports',
    resolution_date: '2026-04-15T23:59:00.000Z',
  },

  // Tennis
  {
    id: 'pm_171',
    question: 'Will Novak Djokovic win any Grand Slam in 2026?',
    resolution_criteria: 'YES if Novak Djokovic wins the Australian Open, French Open, Wimbledon, or US Open in 2026.',
    category: 'sports',
    resolution_date: '2026-09-15T23:59:00.000Z',
  },
  {
    id: 'pm_172',
    question: 'Will Carlos Alcaraz win the 2026 Wimbledon title?',
    resolution_criteria: 'YES if Carlos Alcaraz wins the 2026 Wimbledon Championships men\'s singles title.',
    category: 'sports',
    resolution_date: '2026-07-15T23:59:00.000Z',
  },
  {
    id: 'pm_173',
    question: 'Will Coco Gauff win the 2026 US Open?',
    resolution_criteria: 'YES if Coco Gauff wins the 2026 US Open women\'s singles title.',
    category: 'sports',
    resolution_date: '2026-09-10T23:59:00.000Z',
  },

  // Esports + AI Sports
  {
    id: 'pm_174',
    question: 'Will an AI agent defeat a top-10 chess grandmaster in a 10-game match in 2026?',
    resolution_criteria: 'YES if any AI system (without engine assistance during play) defeats a FIDE top-10 rated grandmaster in a sanctioned 10-game classical chess match in 2026.',
    category: 'sports',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_175',
    question: 'Will an AI agent win a major esports title (Dota 2, CS2, or LoL) in 2026?',
    resolution_criteria: 'YES if any AI-only team or agent wins a Tier 1 esports tournament in Dota 2, Counter-Strike 2, or League of Legends with prize pool >$1M in 2026.',
    category: 'sports',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_176',
    question: 'Will the 2026 League of Legends World Championship exceed 10M peak concurrent viewers?',
    resolution_criteria: 'YES if the 2026 LoL World Championship peak concurrent viewership (Riot Games official + third-party streams combined) exceeds 10,000,000 at any point during the tournament.',
    category: 'sports',
    resolution_date: '2026-11-30T23:59:00.000Z',
  },

  // Olympics 2028 Preview
  {
    id: 'pm_177',
    question: 'Will the USA top the medal table at the 2028 LA Olympics?',
    resolution_criteria: 'YES if the United States leads all nations in total gold medals at the 2028 Los Angeles Summer Olympics.',
    category: 'sports',
    resolution_date: '2028-08-15T23:59:00.000Z',
  },
  {
    id: 'pm_178',
    question: 'Will China win more gold medals than the USA at the 2028 LA Olympics?',
    resolution_criteria: 'YES if China\'s total gold medal count exceeds the United States\' at the conclusion of the 2028 LA Olympics.',
    category: 'sports',
    resolution_date: '2028-08-15T23:59:00.000Z',
  },

  // Boxing / MMA
  {
    id: 'pm_179',
    question: 'Will there be an undisputed heavyweight boxing champion in 2026?',
    resolution_criteria: 'YES if a single boxer holds all four major heavyweight titles simultaneously (WBA, WBC, IBF, WBO) at any point in 2026.',
    category: 'sports',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
  {
    id: 'pm_180',
    question: 'Will Jon Jones fight again in the UFC in 2026?',
    resolution_criteria: 'YES if Jon Jones competes in a UFC-sanctioned fight at any point in 2026.',
    category: 'sports',
    resolution_date: '2026-12-31T23:59:00.000Z',
  },
].map(m => ({
  ...m,
  creator_did: FOUNDER_DID,
  settlement_rail: 'usdc',
  initial_yes: 50,
  initial_no: 50,
}));
